#!/usr/bin/env python3
"""
Generate docs/build-log/STATUS.md from BUILD_PLAN.md.

    python scripts/build_status.py

Generated, not written by hand, for the same reason `.env.example` has a test
that checks it: a status page maintained by remembering to update it is a status
page that is quietly wrong within a fortnight.

BUILD_PLAN.md is the single source. A task counts as done when its header
carries a DONE marker; the build log is found by matching the task id against
docs/build-log/. Run this after finishing a task and commit the result.
"""

from __future__ import annotations

import datetime as dt
import pathlib
import re
import subprocess
import sys

# Windows consoles default to cp1252, which cannot encode the box-drawing and
# tick characters this script prints — `print("✓")` raises UnicodeEncodeError
# and the run dies with a traceback rather than a result. Retarget the stream.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")
ROOT = pathlib.Path(__file__).resolve().parent.parent
PLAN = ROOT / "docs" / "spec" / "BUILD_PLAN.md"
OUT = ROOT / "docs" / "build-log" / "STATUS.md"
LOGS = ROOT / "docs" / "build-log"

OWNERS = {"V": "Vraj", "Y": "Yogesh", "both": "Both"}


def parse_tasks() -> list[dict]:
    """Every task in BUILD_PLAN, in document order, with its phase."""
    text = PLAN.read_text(encoding="utf-8")
    tasks: list[dict] = []
    phase_name = ""

    # A task is a bold header followed immediately by a fenced field block.
    # `[^\n]*` on the suffix matters: with re.S a `.` would swallow newlines and
    # swallow prose that merely mentions a task id.
    pattern = re.compile(
        # Phase headings read "# 4. Foundation — Phase 0 · T-001 … T-007":
        # the name first, so the section number and the phase number are never
        # adjacent. Both halves are captured and recombined below, so STATUS.md
        # still reads "Phase 0 — Foundation".
        r"^# \d+\. (?P<phase_title>[^\n—]+) — (?P<phase>Phases? [^·\n]+?)(?: ·[^\n]*)?$"
        r"|^\*\*(?P<id>T-\d+)\s*·\s*(?P<title>[^*]+?)\*\*(?P<suffix>[^\n]*)\n```\n(?P<body>.*?)\n```",
        re.M | re.S,
    )

    for m in pattern.finditer(text):
        if m.group("phase"):
            phase_name = f'{m.group("phase").strip()} — {m.group("phase_title").strip()}'
            continue

        body = m.group("body")
        # Parsed line by line. A single regex over the whole block lets the
        # value for a line-final field (Owner) run into the next line.
        fields: dict[str, str] = {}
        for line in body.splitlines():
            for key, value in re.findall(
                    r"(Phase|Depends|Est|Owner)\s+([^\s].*?)(?=\s{2,}[A-Z]|$)", line):
                fields.setdefault(key, value.strip())
        suffix = m.group("suffix")

        tasks.append({
            "id": m.group("id"),
            "title": re.sub(r"`", "", m.group("title")).strip(),
            "phase": fields.get("Phase", "?"),
            "phase_name": phase_name,
            "depends": fields.get("Depends", "—"),
            "est": fields.get("Est", "?"),
            "owner": OWNERS.get(fields.get("Owner", ""), fields.get("Owner", "?")),
            "star": "⭐" in suffix,
            "done": "DONE" in suffix,
            "note": (re.search(r"\(([^)]*\d{4}-\d{2}-\d{2})\)", suffix) or [None, ""])[1]
                    if "DONE" in suffix else "",
        })
    return tasks


def build_log_for(task_id: str) -> str | None:
    hits = sorted(LOGS.glob(f"{task_id}-*.md"))
    return hits[0].name if hits else None


def days(est: str) -> float:
    m = re.match(r"([\d.]+)", est)
    return float(m.group(1)) if m else 0.0


def git(*args: str) -> str:
    try:
        return subprocess.run(["git", *args], cwd=ROOT, capture_output=True,
                              text=True, timeout=10).stdout.strip()
    except Exception:
        return ""


def render(tasks: list[dict]) -> str:
    done = [t for t in tasks if t["done"]]
    todo = [t for t in tasks if not t["done"]]
    d_done = sum(days(t["est"]) for t in done)
    d_left = sum(days(t["est"]) for t in todo)
    pct = round(100 * len(done) / len(tasks)) if tasks else 0

    L: list[str] = []
    A = L.append

    A("# Build status")
    A("")
    A("| | |")
    A("|---|---|")
    A(f"| **Generated** | {dt.date.today().isoformat()} — `python scripts/build_status.py` |")
    A("| **Source** | `docs/spec/BUILD_PLAN.md` (do not edit this file by hand) |")
    A(f"| **Tasks complete** | **{len(done)} of {len(tasks)}** ({pct}%) |")
    A(f"| **Effort** | {d_done:g} d done · {d_left:g} d remaining |")
    A(f"| **Branch** | `{git('rev-parse', '--abbrev-ref', 'HEAD')}` |")
    A(f"| **Last commit** | `{git('log', '-1', '--format=%h %s')}` |")
    A("")
    A("Estimates are engineering effort only. They do not include the clinical "
      "content authoring that `BUILD_PLAN` §11.1 rates the real critical path — "
      "see the last section.")
    A("")
    A("---")
    A("")

    # ── phase summary ────────────────────────────────────────────────
    A("## Phases at a glance")
    A("")
    A("| Phase | Tasks | Done | Effort left | Status |")
    A("|---|---:|---:|---:|---|")
    seen: list[str] = []
    for t in tasks:
        if t["phase_name"] not in seen:
            seen.append(t["phase_name"])
    for name in seen:
        group = [t for t in tasks if t["phase_name"] == name]
        g_done = [t for t in group if t["done"]]
        left = sum(days(t["est"]) for t in group if not t["done"])
        if len(g_done) == len(group):
            status = "✅ complete"
        elif g_done:
            status = "🟡 in progress"
        else:
            status = "⬜ not started"
        A(f"| {name} | {len(group)} | {len(g_done)} | {left:g} d | {status} |")
    A("")
    A("---")
    A("")

    # ── per phase detail ─────────────────────────────────────────────
    for name in seen:
        group = [t for t in tasks if t["phase_name"] == name]
        g_done = sum(1 for t in group if t["done"])
        A(f"## {name}")
        A("")
        A(f"*{g_done} of {len(group)} complete*")
        A("")
        A("| | Task | Owner | Est | Depends | Build log |")
        A("|---|---|---|---|---|---|")
        for t in group:
            mark = "✅" if t["done"] else "⬜"
            star = " ⭐" if t["star"] else ""
            log = build_log_for(t["id"])
            log_cell = f"[{t['id']}]({log})" if log else "—"
            title = t["title"] + star
            A(f"| {mark} | **{t['id']}** · {title} | {t['owner']} | {t['est']} "
              f"| {t['depends']} | {log_cell} |")
        A("")

    A("---")
    A("")
    A("⭐ marks a task the plan flags as load-bearing — it protects a property "
      "in `CLAUDE.md`, unblocks another track, or closes a known risk.")
    A("")
    A("A task shows ✅ only when its BUILD_PLAN entry carries a DONE marker. "
      "Every completed task has a build log recording what was actually built, "
      "where it diverged from the specification, and what debt it left.")
    A("")
    A("**Phases 5–7 are not listed.** `BUILD_PLAN` §9 summarises them as prose "
      "rather than itemised tasks — measurement upgrade (11 d), mobile (20 d) "
      "and Case Factory (22 d) — and they are expanded when the phase begins. "
      "The counts above therefore cover the work through launch, which is what "
      "there is to track today.")
    A("")
    A("---")
    A("")
    A("## The thing this table cannot show")
    A("")
    A("Every number above is engineering effort. **Ten clinically reviewed "
      "cases gate launch and five exist.** No task in this plan produces one: "
      "writing a case is clinical authoring, not development, and it needs no "
      "developer time.")
    A("")
    A("The two clinician reviewers cannot start until **T-021** (case editor) "
      "and **T-023** (review workflow) exist, because until then only a "
      "programmer can read a case. That is 12 days of Phase 2 work away, and "
      "authoring the drafts can begin before it.")
    A("")
    A("`BUILD_PLAN` §11.1 rates this **the** risk to the schedule, and it is "
      "the one a task tracker makes easy to forget — because it has no task.")
    A("")
    return "\n".join(L)


def main() -> None:
    tasks = parse_tasks()
    OUT.write_text(render(tasks) + "\n", encoding="utf-8")
    done = sum(1 for t in tasks if t["done"])
    print(f"Wrote {OUT.relative_to(ROOT)} — {done}/{len(tasks)} tasks complete")


if __name__ == "__main__":
    main()
